name: t5-lora-env
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - sacrebleu
  - json5  # for robust JSON handling
  - pip
  - pip:
      - transformers
      - datasets
      - peft